export enum BusinessLicenseStatus {
  PENDING_SUBMISSION = 'PENDING_SUBMISSION',
  UNDER_TECH_REVIEW = 'UNDER_TECH_REVIEW',
  UNDER_FINANCE_REVIEW = 'UNDER_FINANCE_REVIEW',
  UNDER_HEALTH_REVIEW = 'UNDER_HEALTH_REVIEW',
  SUPERVISOR_REVIEW = 'SUPERVISOR_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}